#!/usr/bin/env bash
#
#       Copyright (c) 2023 German Aerospace Center DLR e.V. (GSOC)
#
#       Licensed under the Apache License, Version 2.0 (the "License");
#       you may not use this file except in compliance with the License.
#       You may obtain a copy of the License at
#
#               http://www.apache.org/licenses/LICENSE-2.0
#
#       Unless required by applicable law or agreed to in writing, software
#       distributed under the License is distributed on an "AS IS" BASIS,
#       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#       See the License for the specific language governing permissions and
#       limitations under the License.
#
#       This file is part of the openvocs project. http://openvocs.org
#
#       ------------------------------------------------------------------------
#
#       Usage           ov_letsencrypt.sh <domain> [email] [mode] [azure_ini_path]
#
#                        Obtains (or renews) a Let's Encrypt certificate for
#                        <domain> via a DNS-01 challenge, then links it into
#                        the openvocs config directory under the name
#                        ov_config.sh expects ($DOMAIN.crt / $DOMAIN.key), so
#                        it is a drop-in replacement for the self signed
#                        certificate generated by ov_config.sh.
#
#                        DNS-01 does not require the host to be reachable
#                        from the internet at all (unlike HTTP-01), which
#                        makes it work for hosts that are only reachable via
#                        a private network / VPN (e.g. a Tailscale address).
#
#                        mode selects how the DNS-01 challenge is fulfilled,
#                        defaults to "azure":
#
#                        azure   Fully automated via the Azure DNS API
#                                (certbot-dns-azure plugin). Requires Azure
#                                credentials in azure_ini_path (defaults to
#                                /etc/letsencrypt/azure.ini - a template is
#                                written there on first run if missing, see
#                                https://github.com/terricain/certbot-dns-azure
#                                for the full set of options). Runs fully
#                                unattended and auto-renews via certbot's own
#                                timer.
#
#                        manual  Works with any DNS provider. certbot prints
#                                a TXT record for you to add by hand, then
#                                waits for confirmation before continuing.
#                                Must be run interactively, and since it is
#                                manual, certbot's renewal timer cannot renew
#                                it unattended - re-run this script before
#                                the certificate expires (90 days).
#
#       ------------------------------------------------------------------------

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit 1
fi

if [[ -z "$1" ]]; then
    echo "Usage: $0 <domain> [email] [azure|manual] [azure_ini_path]"
    echo "Example: $0 vocs.space-cu.net admin@space-cu.com azure"
    echo "Example: $0 vocs.space-cu.net admin@space-cu.com manual"
    exit 1
fi

DOMAIN=$1
EMAIL=$2
MODE=${3:-azure}

DIR_CONFIG="/etc/openvocs"
DIR_OV_MC_VOCS=$DIR_CONFIG/ov_mc_vocs

if [ ! -d "$DIR_OV_MC_VOCS" ]; then
    echo "$DIR_OV_MC_VOCS does not exist - run ov_config.sh first."
    exit 1
fi

if [ "$MODE" != "azure" ] && [ "$MODE" != "manual" ]; then
    echo "Unknown mode '$MODE', expected 'azure' or 'manual'"
    exit 1
fi

# certbot is installed via pipx (an isolated venv) rather than apt or a bare
# pip install, so installing the certbot-dns-azure plugin can never conflict
# with the system's own Python packages (apt's Python is "externally
# managed" on modern Debian/Ubuntu specifically to prevent this).
if ! command -v pipx >/dev/null 2>&1; then
    echo "pipx not found, installing..."
    apt-get update && apt-get install -y pipx
fi

if ! pipx list --short 2>/dev/null | grep -q '^certbot '; then
    echo "certbot not found, installing via pipx..."
    pipx install certbot
fi

PIPX_BIN_DIR=$(pipx environment --value PIPX_BIN_DIR 2>/dev/null)
CERTBOT="${PIPX_BIN_DIR:-$HOME/.local/bin}/certbot"

EMAIL_ARG="--register-unsafely-without-email"
if [ "X" != "X$EMAIL" ]; then
    EMAIL_ARG="-m $EMAIL"
fi

if [ "$MODE" = "azure" ]; then

    AZURE_INI=${4:-/etc/letsencrypt/azure.ini}

    if [ ! -f "$AZURE_INI" ]; then

        mkdir -p "$(dirname "$AZURE_INI")"

        echo "# Azure DNS credentials for certbot-dns-azure - fill in and re-run this script.
#
# Pick ONE authentication method below and delete the others.
#
# Option 1) Service Principal
# dns_azure_sp_client_id = <client id>
# dns_azure_sp_client_secret = <client secret>
# dns_azure_tenant_id = <tenant id>
#
# Option 2) System assigned Managed Identity (only works when this VM runs in Azure
# and has been granted a system assigned identity with 'DNS Zone Contributor' on the
# resource group below)
# dns_azure_msi_system_assigned = true
#
# Option 3) User assigned Managed Identity
# dns_azure_msi_client_id = <managed identity client id>

# Required: maps this domain to the Azure resource group containing its DNS zone.
dns_azure_zone1 = $DOMAIN:/subscriptions/<subscription id>/resourceGroups/<resource group name>
" > "$AZURE_INI"

        chmod 600 "$AZURE_INI"

        echo "No Azure credentials found - wrote a template to $AZURE_INI"
        echo "Edit it with your Azure credentials and DNS zone resource group, then re-run this script."
        exit 1
    fi

    chmod 600 "$AZURE_INI"

    if ! "$CERTBOT" plugins --text 2>/dev/null | grep -q dns-azure; then
        echo "certbot-dns-azure plugin not found, installing into certbot's pipx venv..."
        pipx inject certbot certbot-dns-azure
    fi

    # acme (a core certbot dependency) still relies on josepy's legacy
    # ComparableX509, which in turn needs OpenSSL.crypto.X509Req via
    # pyOpenSSL - a version dropped from recent pyOpenSSL releases, crashing
    # certbot on startup with "module 'OpenSSL.crypto' has no attribute
    # 'X509Req'". Pin pyOpenSSL back to a version that still has it, and let
    # josepy resolve naturally to a version that still has ComparableX509
    # (josepy>=2 removed it, which breaks acme the other way).
    if ! "$CERTBOT" --version >/dev/null 2>&1; then
        echo "certbot is broken (likely a pyOpenSSL/cryptography mismatch), pinning a compatible pyOpenSSL..."
        pipx inject certbot 'pyOpenSSL<24' 'josepy<2' --force
    fi

    # pipx-installed certbot has no systemd renewal timer of its own (unlike
    # the apt package), so set one up here to keep auto-renewal working.
    if [ ! -f /etc/systemd/system/ov_certbot_renew.timer ]; then

        echo "[Unit]
Description=Renew Let's Encrypt certificates (pipx certbot)

[Service]
Type=oneshot
ExecStart=$CERTBOT renew --quiet
" > /etc/systemd/system/ov_certbot_renew.service

        echo "[Unit]
Description=Twice daily renewal check for pipx certbot

[Timer]
OnCalendar=*-*-* 00,12:00:00
RandomizedDelaySec=3600
Persistent=true

[Install]
WantedBy=timers.target
" > /etc/systemd/system/ov_certbot_renew.timer

        systemctl daemon-reload
        systemctl enable --now ov_certbot_renew.timer
    fi

    echo "Requesting Let's Encrypt certificate for $DOMAIN via Azure DNS ..."

    "$CERTBOT" certonly \
        --authenticator dns-azure \
        --dns-azure-config "$AZURE_INI" \
        --preferred-challenges dns \
        --non-interactive \
        --agree-tos \
        $EMAIL_ARG \
        --deploy-hook "systemctl restart ov_mc_vocs ov_mc_ice_proxy" \
        -d "$DOMAIN"

else

    echo "Requesting Let's Encrypt certificate for $DOMAIN via manual DNS-01 ..."
    echo "You will be prompted to add a TXT record to the PUBLIC DNS zone for"
    echo "this domain. This script must be run interactively."
    echo ""

    "$CERTBOT" certonly --manual \
        --preferred-challenges dns \
        --manual-public-ip-logging-ok \
        --agree-tos \
        $EMAIL_ARG \
        --deploy-hook "systemctl restart ov_mc_vocs ov_mc_ice_proxy" \
        -d "$DOMAIN"

fi

if [ $? -ne 0 ]; then
    echo "certbot failed to obtain a certificate for $DOMAIN"
    exit 1
fi

LE_DIR="/etc/letsencrypt/live/$DOMAIN"

ln -sf "$LE_DIR/fullchain.pem" "$DIR_OV_MC_VOCS/$DOMAIN.crt"
ln -sf "$LE_DIR/privkey.pem" "$DIR_OV_MC_VOCS/$DOMAIN.key"

echo ""
echo "Certificate installed:"
echo "  $DIR_OV_MC_VOCS/$DOMAIN.crt -> $LE_DIR/fullchain.pem"
echo "  $DIR_OV_MC_VOCS/$DOMAIN.key -> $LE_DIR/privkey.pem"
echo ""
echo "!!! NOTE !!!"
echo ""
echo "Re-running ov_config.sh will overwrite these files with a new self"
echo "signed certificate. Run this script again afterwards to restore the"
echo "Let's Encrypt certificate."
echo ""

if [ "$MODE" = "azure" ]; then
    echo "Certbot will auto-renew via its own systemd timer/cron job and"
    echo "restart ov_mc_vocs / ov_mc_ice_proxy automatically on renewal."
else
    echo "This certificate was issued via the manual DNS-01 challenge, so"
    echo "certbot's automatic renewal timer CANNOT renew it unattended."
    echo "Re-run this script before it expires (90 days) to renew it."
fi
